package postgres

import (
	"context"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"

	"flowed/internal/domain/shared"
	"flowed/internal/domain/student"
	"flowed/internal/platform/pg"
	"flowed/internal/port"
)

// StudentRepository stores student identity.
type StudentRepository struct{ db *pg.DB }

// NewStudentRepository builds the student store over a connection pool.
func NewStudentRepository(db *pg.DB) *StudentRepository { return &StudentRepository{db: db} }

var _ port.StudentRepository = (*StudentRepository)(nil)

const studentColumns = `
	id, student_no, full_name, mother_name, birth_date, gender,
	phone, phone_alt, email, address, guardian_name, guardian_phone,
	first_admission_year, status, merged_into_id, notes,
	created_at, updated_at, created_by`

// scanStudent reads one student row. Extra destinations are appended for the
// queries that select a computed column alongside the entity, so the column
// order lives in exactly one place.
func scanStudent(row pgx.Row, extra ...any) (*student.Student, error) {
	var (
		s         student.Student
		birthDate *time.Time
		gender    *string
	)
	dest := []any{
		&s.ID, &s.StudentNo, &s.FullName, &s.MotherName, &birthDate, &gender,
		&s.Phone, &s.PhoneAlt, &s.Email, &s.Address, &s.GuardianName, &s.GuardianPhone,
		&s.FirstAdmissionYear, &s.Status, &s.MergedIntoID, &s.Notes,
		&s.CreatedAt, &s.UpdatedAt, &s.CreatedBy,
	}
	if err := row.Scan(append(dest, extra...)...); err != nil {
		return nil, err
	}
	s.BirthDate = dateOrNil(birthDate)
	s.Gender = enumPtr[student.Gender](gender)
	return &s, nil
}

// Create records a new person. The folded search columns are generated by the
// database, so no code path can store a name that was not folded.
func (r *StudentRepository) Create(ctx context.Context, s *student.Student) error {
	if err := r.db.RequireTx(ctx, "student.Create"); err != nil {
		return err
	}
	const query = `
		INSERT INTO student (
			id, student_no, full_name, mother_name, birth_date, gender,
			phone, phone_alt, email, address, guardian_name, guardian_phone,
			first_admission_year, status, merged_into_id, notes, created_by
		) VALUES (
			$1, $2, $3, $4, $5, $6,
			$7, $8, $9, $10, $11, $12,
			$13, $14, $15, $16, $17
		)
		RETURNING created_at, updated_at`

	q := r.db.Conn(ctx)
	err := q.QueryRow(ctx, query,
		s.ID, s.StudentNo, s.FullName, s.MotherName, timeOrNil(s.BirthDate), enumValue(s.Gender),
		s.Phone, s.PhoneAlt, s.Email, s.Address, s.GuardianName, s.GuardianPhone,
		s.FirstAdmissionYear, s.Status, s.MergedIntoID, s.Notes, s.CreatedBy,
	).Scan(&s.CreatedAt, &s.UpdatedAt)
	return pg.WrapQuery("student.Create", err)
}

// Update overwrites the current identity and contact details. Documented
// identity changes are additionally appended as versions; this row is only the
// denormalised current state.
func (r *StudentRepository) Update(ctx context.Context, s *student.Student) error {
	if err := r.db.RequireTx(ctx, "student.Update"); err != nil {
		return err
	}
	const query = `
		UPDATE student SET
			student_no           = $2,
			full_name            = $3,
			mother_name          = $4,
			birth_date           = $5,
			gender               = $6,
			phone                = $7,
			phone_alt            = $8,
			email                = $9,
			address              = $10,
			guardian_name        = $11,
			guardian_phone       = $12,
			first_admission_year = $13,
			status               = $14,
			merged_into_id       = $15,
			notes                = $16
		WHERE id = $1
		RETURNING updated_at`

	q := r.db.Conn(ctx)
	err := q.QueryRow(ctx, query,
		s.ID, s.StudentNo, s.FullName, s.MotherName, timeOrNil(s.BirthDate), enumValue(s.Gender),
		s.Phone, s.PhoneAlt, s.Email, s.Address, s.GuardianName, s.GuardianPhone,
		s.FirstAdmissionYear, s.Status, s.MergedIntoID, s.Notes,
	).Scan(&s.UpdatedAt)
	return pg.WrapQuery("student.Update", err)
}

// GetByID returns one student.
func (r *StudentRepository) GetByID(ctx context.Context, id shared.ID) (*student.Student, error) {
	q := r.db.Conn(ctx)
	s, err := scanStudent(q.QueryRow(ctx, `SELECT`+studentColumns+` FROM student WHERE id = $1`, id))
	if err != nil {
		return nil, pg.WrapQuery("student.GetByID", err)
	}
	return s, nil
}

// GetByStudentNo returns the student holding a university number.
func (r *StudentRepository) GetByStudentNo(ctx context.Context, studentNo string) (*student.Student, error) {
	q := r.db.Conn(ctx)
	s, err := scanStudent(q.QueryRow(ctx, `SELECT`+studentColumns+` FROM student WHERE student_no = $1`, studentNo))
	if err != nil {
		return nil, pg.WrapQuery("student.GetByStudentNo", err)
	}
	return s, nil
}

// FindPossibleDuplicates looks for the same person under a second record.
//
// A shared full name alone is not a duplicate: four-part Iraqi names repeat
// constantly, and returning every namesake would train registrars to dismiss
// the warning. The candidate set is therefore students whose folded name
// matches and who also share the mother's name — the discriminator registrars
// actually use — or, when one was supplied, the birth date.
func (r *StudentRepository) FindPossibleDuplicates(
	ctx context.Context, fullName, motherName string, birthDate *shared.Date,
) ([]*student.Student, error) {
	const query = `
		SELECT` + studentColumns + `
		FROM student
		WHERE full_name_norm = normalize_arabic($1)
		  AND (
		        mother_name_norm = normalize_arabic($2)
		     OR ($3::date IS NOT NULL AND birth_date = $3)
		  )
		ORDER BY created_at
		LIMIT 50`

	q := r.db.Conn(ctx)
	rows, err := q.Query(ctx, query, fullName, motherName, timeOrNil(birthDate))
	if err != nil {
		return nil, pg.WrapQuery("student.FindPossibleDuplicates", err)
	}
	found, err := pgx.CollectRows(rows, func(row pgx.CollectableRow) (*student.Student, error) {
		return scanStudent(row)
	})
	if err != nil {
		return nil, pg.WrapQuery("student.FindPossibleDuplicates", err)
	}
	return found, nil
}

// Search queries the student index and returns one page plus the full match
// count.
func (r *StudentRepository) Search(ctx context.Context, s port.StudentSearch) ([]*student.Student, int, error) {
	args := &argList{}
	where, prefixMatch := r.searchPredicates(s, args)

	limit := boundedLimit(s.Limit, 50)
	offset := max(s.Offset, 0)

	// Prefix matches on the folded name lead the page, ahead of the substring
	// matches that share it: a clerk typing the start of a name expects the
	// names that start that way first.
	order := "s.full_name_norm, s.student_no"
	if prefixMatch != "" {
		order = "(" + prefixMatch + ") DESC, " + order
	}

	// count(*) OVER () rides along with the page, so the common case costs one
	// query rather than two.
	query := `
		SELECT` + studentColumns + `, count(*) OVER () AS total_count
		FROM student s
		WHERE ` + strings.Join(where, "\n\t\t  AND ") + `
		ORDER BY ` + order + `
		LIMIT ` + args.next(limit) + ` OFFSET ` + args.next(offset)

	q := r.db.Conn(ctx)
	rows, err := q.Query(ctx, query, args.all()...)
	if err != nil {
		return nil, 0, pg.WrapQuery("student.Search", err)
	}

	var total int64
	found, err := pgx.CollectRows(rows, func(row pgx.CollectableRow) (*student.Student, error) {
		return scanStudent(row, &total)
	})
	if err != nil {
		return nil, 0, pg.WrapQuery("student.Search", err)
	}

	// An empty page past the end of the result set carries no window count, so
	// a paginator that overshot would be told there were no matches at all.
	if len(found) == 0 && offset > 0 {
		countArgs := &argList{}
		countWhere, _ := r.searchPredicates(s, countArgs)
		countQuery := `SELECT count(*) FROM student s WHERE ` + strings.Join(countWhere, "\n\t\t  AND ")
		if err := q.QueryRow(ctx, countQuery, countArgs.all()...).Scan(&total); err != nil {
			return nil, 0, pg.WrapQuery("student.Search.count", err)
		}
	}

	return found, int(total), nil
}

// searchPredicates builds the WHERE clause shared by the page query and the
// count fallback, recording each value as a positional parameter. It also
// returns the boolean expression that identifies a prefix match, which the
// page query sorts on and the count query ignores.
func (r *StudentRepository) searchPredicates(s port.StudentSearch, args *argList) (where []string, prefixMatch string) {
	where = []string{"true"}

	if term := strings.TrimSpace(s.Query); term != "" {
		// The raw term answers the exact comparisons; the escaped copy answers
		// the LIKE patterns. Both sides of every name comparison run through
		// normalize_arabic, which is the same function the generated columns
		// were written with.
		raw := args.next(term)
		rawAgain := args.next(term)
		pattern := args.next(likeEscape(term))
		where = append(where, `(
		        s.full_name_norm   LIKE normalize_arabic(`+pattern+`) || '%'
		     OR s.mother_name_norm LIKE normalize_arabic(`+pattern+`) || '%'
		     OR s.full_name_norm   LIKE '%' || normalize_arabic(`+pattern+`) || '%'
		     OR s.mother_name_norm LIKE '%' || normalize_arabic(`+pattern+`) || '%'
		     OR s.student_no       = `+raw+`
		     OR s.phone_norm       = normalize_phone(`+raw+`)
		     OR s.phone_alt_norm   = normalize_phone(`+raw+`)
		     OR (
		          length(phone_digits(`+rawAgain+`)) >= 3
		          AND s.phone_rev LIKE reverse_text(phone_digits(`+rawAgain+`)) || '%'
		        )
		  )`)
		prefixMatch = "s.full_name_norm LIKE normalize_arabic(" + pattern + ") || '%'"
	}

	if s.Status != nil {
		where = append(where, "s.status = "+args.next(string(*s.Status)))
	}

	// The academic dimensions live on the enrollment, not the person. Superseded
	// rows are excluded so a student who moved department in March is not still
	// found under the department they left.
	var seat []string
	if s.AcademicYearID != nil {
		seat = append(seat, "e.academic_year_id = "+args.next(*s.AcademicYearID))
	}
	if s.CollegeID != nil {
		seat = append(seat, "e.college_id = "+args.next(*s.CollegeID))
	}
	if s.DepartmentID != nil {
		seat = append(seat, "e.department_id = "+args.next(*s.DepartmentID))
	}
	if s.StudyTypeID != nil {
		seat = append(seat, "e.study_type_id = "+args.next(*s.StudyTypeID))
	}
	if s.Stage != nil {
		seat = append(seat, "e.stage = "+args.next(*s.Stage))
	}
	if len(seat) > 0 {
		where = append(where, `EXISTS (
		        SELECT 1 FROM enrollment e
		        WHERE e.student_id = s.id
		          AND e.enrollment_status <> 'superseded'
		          AND `+strings.Join(seat, " AND ")+`
		  )`)
	}

	// Organisational scope. A student is visible when any of their
	// non-superseded enrollments sits in a college or department the caller
	// holds — a student who transferred out of engineering into medicine is
	// visible to both, which is correct: both of them taught the person and
	// both hold money against them.
	if predicate := scopeExists(s.Scope, args, "s.id"); predicate != "" {
		where = append(where, predicate)
	}

	if s.OnlyWithDebt {
		// Mirrors the ix_account_outstanding predicate exactly, so the partial
		// index can serve it.
		where = append(where, `EXISTS (
		        SELECT 1 FROM financial_account fa
		        WHERE fa.student_id = s.id
		          AND fa.status IN ('active', 'pending')
		          AND (fa.net_total + fa.adjustment_total) > (fa.paid_total - fa.refunded_total)
		  )`)
	}

	return where, prefixMatch
}

// AppendIdentityVersion records a documented identity change. The rows are
// append-only and the database refuses both update and delete on them.
func (r *StudentRepository) AppendIdentityVersion(ctx context.Context, v *student.IdentityVersion) error {
	if err := r.db.RequireTx(ctx, "student.AppendIdentityVersion"); err != nil {
		return err
	}
	const query = `
		INSERT INTO student_identity_version (
			id, student_id, version_no, full_name, mother_name,
			birth_date, birth_place, gender, nationality, effective_from,
			court_decision_no, court_decision_date, document_ref, change_reason,
			recorded_at, recorded_by
		) VALUES (
			$1, $2, $3, $4, $5,
			$6, $7, $8, $9, $10,
			$11, $12, $13, $14,
			COALESCE($15, now()), $16
		)
		RETURNING recorded_at`

	q := r.db.Conn(ctx)
	err := q.QueryRow(ctx, query,
		v.ID, v.StudentID, v.VersionNo, v.FullName, v.MotherName,
		timeOrNil(v.BirthDate), v.BirthPlace, enumValue(v.Gender), v.Nationality, v.EffectiveFrom.Time(),
		v.CourtDecisionNo, timeOrNil(v.CourtDecisionDate), v.DocumentRef, v.ChangeReason,
		instant(v.RecordedAt), v.RecordedBy,
	).Scan(&v.RecordedAt)
	return pg.WrapQuery("student.AppendIdentityVersion", err)
}

// IdentityHistory returns every recorded identity for a student, oldest first.
func (r *StudentRepository) IdentityHistory(ctx context.Context, studentID shared.ID) ([]*student.IdentityVersion, error) {
	const query = `
		SELECT id, student_id, version_no, full_name, mother_name,
		       birth_date, birth_place, gender, nationality, effective_from,
		       court_decision_no, court_decision_date, document_ref, change_reason,
		       recorded_at, recorded_by
		FROM student_identity_version
		WHERE student_id = $1
		ORDER BY version_no`

	q := r.db.Conn(ctx)
	rows, err := q.Query(ctx, query, studentID)
	if err != nil {
		return nil, pg.WrapQuery("student.IdentityHistory", err)
	}
	history, err := pgx.CollectRows(rows, func(row pgx.CollectableRow) (*student.IdentityVersion, error) {
		var (
			v             student.IdentityVersion
			birthDate     *time.Time
			gender        *string
			effectiveFrom time.Time
			decisionDate  *time.Time
		)
		if err := row.Scan(
			&v.ID, &v.StudentID, &v.VersionNo, &v.FullName, &v.MotherName,
			&birthDate, &v.BirthPlace, &gender, &v.Nationality, &effectiveFrom,
			&v.CourtDecisionNo, &decisionDate, &v.DocumentRef, &v.ChangeReason,
			&v.RecordedAt, &v.RecordedBy,
		); err != nil {
			return nil, err
		}
		v.BirthDate = dateOrNil(birthDate)
		v.Gender = enumPtr[student.Gender](gender)
		v.EffectiveFrom = shared.DateFromTime(effectiveFrom)
		v.CourtDecisionDate = dateOrNil(decisionDate)
		return &v, nil
	})
	if err != nil {
		return nil, pg.WrapQuery("student.IdentityHistory", err)
	}
	return history, nil
}

// CurrentEnrollmentSummaries batches port.CurrentEnrollmentSummary lookups for
// a page of students into one query: DISTINCT ON picks, per student, the
// non-superseded enrollment whose academic year started most recently.
func (r *StudentRepository) CurrentEnrollmentSummaries(
	ctx context.Context, studentIDs []shared.ID,
) (map[shared.ID]port.CurrentEnrollmentSummary, error) {
	result := make(map[shared.ID]port.CurrentEnrollmentSummary, len(studentIDs))
	if len(studentIDs) == 0 {
		return result, nil
	}

	const query = `
		SELECT DISTINCT ON (e.student_id)
		       e.student_id, e.study_type_id, st.code, e.stage, e.academic_year_id
		FROM enrollment e
		JOIN academic_year y ON y.id = e.academic_year_id
		JOIN study_type st ON st.id = e.study_type_id
		WHERE e.student_id = ANY($1) AND e.enrollment_status <> 'superseded'
		ORDER BY e.student_id, y.start_date DESC, e.sequence_no DESC`

	q := r.db.Conn(ctx)
	rows, err := q.Query(ctx, query, studentIDs)
	if err != nil {
		return nil, pg.WrapQuery("student.CurrentEnrollmentSummaries", err)
	}
	defer rows.Close()

	for rows.Next() {
		var (
			studentID shared.ID
			summary   port.CurrentEnrollmentSummary
		)
		if err := rows.Scan(&studentID, &summary.StudyTypeID, &summary.StudyTypeCode,
			&summary.Stage, &summary.AcademicYearID); err != nil {
			return nil, pg.WrapQuery("student.CurrentEnrollmentSummaries", err)
		}
		result[studentID] = summary
	}
	if err := rows.Err(); err != nil {
		return nil, pg.WrapQuery("student.CurrentEnrollmentSummaries", err)
	}
	return result, nil
}

// scopeExists renders a scope filter as an EXISTS predicate over enrollment.
//
// An unrestricted scope adds nothing. A restricted scope with no grants
// produces "false", which returns an empty page rather than everything: a
// filter that fails open is not a filter.
func scopeExists(filter shared.ScopeFilter, args *argList, studentColumn string) string {
	if filter.Unrestricted() {
		return ""
	}
	if filter.Empty() {
		return "false"
	}

	var clauses []string
	if len(filter.Colleges) > 0 {
		clauses = append(clauses, "e.college_id = ANY("+args.next(filter.Colleges)+")")
	}
	if len(filter.Departments) > 0 {
		clauses = append(clauses, "e.department_id = ANY("+args.next(filter.Departments)+")")
	}
	return `EXISTS (
		        SELECT 1 FROM enrollment e
		        WHERE e.student_id = ` + studentColumn + `
		          AND e.enrollment_status <> 'superseded'
		          AND (` + strings.Join(clauses, " OR ") + `)
		  )`
}
