package httpapi

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gin-gonic/gin"
)

// specPath is where the checked-in document lives. It is generated by
// `make openapi` and read by clients; this test is what stops it drifting.
const specPath = "../../../api/openapi.json"

// TestOpenAPIMatchesTheRouter is the drift guard.
//
// A hand-maintained specification is wrong within a week of somebody adding an
// endpoint in a hurry, and a client generated from a wrong specification fails
// in a way that looks like a server bug. This regenerates from the live router
// and compares against the checked-in file, so adding a route without
// regenerating fails the build rather than the integration.
func TestOpenAPIMatchesTheRouter(t *testing.T) {
	generated := generateSpecJSON(t)

	onDisk, err := os.ReadFile(specPath)
	if err != nil {
		t.Fatalf("the API contract is missing (%v).\nRun: make openapi", err)
	}

	if normalise(string(onDisk)) != normalise(generated) {
		t.Fatalf("the checked-in API contract no longer matches the router.\n" +
			"Run: make openapi\n" +
			"Then review the diff — a route that changed shape is a change every client sees.")
	}
}

// TestEveryRouteIsInTheSpec catches the reverse drift: a route the generator
// skipped for any reason would otherwise be invisible to every client.
func TestEveryRouteIsInTheSpec(t *testing.T) {
	engine := testRouter(t)
	spec := BuildSpec(engine, "test")

	for _, route := range engine.Routes() {
		// The interface shell is deliberately absent; see BuildSpec.
		if strings.HasPrefix(route.Path, "/app/") {
			continue
		}
		item, ok := spec.Paths[route.Path]
		if !ok {
			t.Errorf("%s %s is served but absent from the specification", route.Method, route.Path)
			continue
		}
		if _, ok := item[strings.ToLower(route.Method)]; !ok {
			t.Errorf("%s is served on %s but that method is absent from the specification",
				route.Method, route.Path)
		}
	}
}

// TestPublicRoutesAreDeclaredPublic proves the specification agrees with the
// router about which endpoints need no credential — the property a reader is
// most likely to trust without checking.
func TestPublicRoutesAreDeclaredPublic(t *testing.T) {
	engine := testRouter(t)
	spec := BuildSpec(engine, "test")

	for path, item := range spec.Paths {
		for method, operation := range item {
			key := strings.ToUpper(method) + " " + path
			expectPublic := publicPaths[key] || operationMetadata[key].Public

			isPublic := operation.Security != nil && len(operation.Security) == 0
			if expectPublic != isPublic {
				t.Errorf("%s: specification says public=%t, router says public=%t",
					key, isPublic, expectPublic)
			}
		}
	}

	// The list itself is worth asserting: an endpoint quietly added to it is
	// an endpoint quietly opened to the internet.
	wantPublic := []string{
		"GET /health", "GET /ready",
		"POST /api/v1/auth/login", "POST /api/v1/auth/refresh",
		"POST /webhooks/payments/:provider", "GET /verify/statement/:code",
		// The desk list: a cashier cannot obtain a token without naming a desk,
		// so the sign-in form needs it before anybody is signed in. It carries a
		// code and an Arabic name, both printed on every receipt.
		"GET /api/v1/public/cashier-desks",
	}
	if len(publicPaths) != len(wantPublic) {
		t.Errorf("the public route list has %d entries, expected %d — every addition opens "+
			"something to the internet and should be deliberate", len(publicPaths), len(wantPublic))
	}
	for _, key := range wantPublic {
		if !publicPaths[key] {
			t.Errorf("%s should be public", key)
		}
	}
}

// TestMoneyIsDocumentedAsAnInteger guards the single most costly
// misunderstanding a client can have about this API.
func TestMoneyIsDocumentedAsAnInteger(t *testing.T) {
	spec := BuildSpec(testRouter(t), "test")

	schema, ok := spec.Components.Schemas["RecordPaymentRequest"]
	if !ok {
		t.Fatal("the payment request schema was not generated")
	}
	amount, ok := schema.Properties["amount"]
	if !ok {
		t.Fatal("the payment request has no amount property")
	}
	if amount.Type != "integer" {
		t.Errorf("amount is documented as %q; a client generator producing a float would "+
			"eventually lose a dinar", amount.Type)
	}
	if !strings.Contains(strings.ToLower(spec.Info.Description), "dinar") {
		t.Error("the specification should say that money is whole dinars")
	}
}

// TestIdempotentOperationsDocumentTheHeader: a client that omits the header on
// a money-moving POST gets a 400 it cannot explain.
func TestIdempotentOperationsDocumentTheHeader(t *testing.T) {
	spec := BuildSpec(testRouter(t), "test")

	for _, key := range []string{"POST /api/v1/payments", "POST /api/v1/accounts"} {
		parts := strings.SplitN(key, " ", 2)
		operation, ok := spec.Paths[parts[1]][strings.ToLower(parts[0])]
		if !ok {
			t.Errorf("%s is not in the specification", key)
			continue
		}
		found := false
		for _, parameter := range operation.Parameters {
			if parameter.In == "header" && parameter.Name == "Idempotency-Key" {
				found = true
			}
		}
		if !found {
			t.Errorf("%s moves money but does not document the Idempotency-Key header", key)
		}
	}
}

// generateSpecJSON renders the specification exactly as `make openapi` does.
func generateSpecJSON(t *testing.T) string {
	t.Helper()
	spec := BuildSpec(testRouter(t), "generated")

	encoded, err := json.MarshalIndent(spec, "", "  ")
	if err != nil {
		t.Fatalf("encoding the specification: %v", err)
	}
	return string(encoded) + "\n"
}

// testRouter builds the engine with every handler group mounted.
//
// The handlers are nil: BuildSpec reads the route table, not the handlers, and
// a nil handler is never called. What matters is that every Register call runs,
// because a route group somebody forgot to mount here would be a route group
// missing from the specification and nobody would notice.
func testRouter(t *testing.T) *gin.Engine {
	t.Helper()
	gin.SetMode(gin.TestMode)
	return NewSpecRouter()
}

// normalise ignores trailing whitespace differences between the file and the
// generated bytes.
func normalise(s string) string { return strings.TrimSpace(s) }

var _ = filepath.Join
